# Generated by Django 3.2.5 on 2021-07-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0002_auto_20210704_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='story',
            name='last_updated_on',
        ),
    ]
