# Generated by Django 3.2.5 on 2021-07-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0003_auto_20210704_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='media/story-images')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_image', to='social_media_app.story')),
            ],
        ),
    ]
