# Generated by Django 3.2.5 on 2021-07-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0006_storystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storystatus',
            old_name='story',
            new_name='story_id',
        ),
    ]
