# Generated by Django 3.2.5 on 2021-07-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0008_alter_story_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
